// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CartItem cart item
//
// swagger:model Cart_Item
type CartItem struct {

	// cart id
	CartID int64 `json:"cart_id,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// price
	Price int32 `json:"price,omitempty"`

	// product id
	ProductID int64 `json:"product_id,omitempty"`

	// quantity
	Quantity int32 `json:"quantity,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this cart item
func (m *CartItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cart item based on context it is used
func (m *CartItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CartItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CartItem) UnmarshalBinary(b []byte) error {
	var res CartItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
