// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Cart cart
//
// swagger:model Cart
type Cart struct {

	// id
	ID int64 `json:"id,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this cart
func (m *Cart) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cart based on context it is used
func (m *Cart) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Cart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Cart) UnmarshalBinary(b []byte) error {
	var res Cart
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
